kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-delete
  namespace: zfs-system
spec:
  storageClassName: zfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128M
