kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-nfs
  namespace: zfs-system
spec:
  storageClassName: zfs-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128M
