---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example
  annotations:
    volume.beta.kubernetes.io/storage-class: "zfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G