---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zfs
provisioner: gentics.com/zfs
reclaimPolicy: Delete
parameters:
  parentDataset: test/volumes
  shareSubnet: 192.168.99.0/24
  hostname: 192.168.99.1