---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zfs
provisioner: gentics.com/zfs
reclaimPolicy: Delete
parameters:
  # parentDataset and shareSubnet are mandatory.
  parentDataset: test/volumes 
  shareSubnet: 10.0.0.0/8
