# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- env:
  - CGO_ENABLED=0 # this is needed to build the single binary
  goarch:
  - amd64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
- image_templates:
  - "docker.io/ccremer/zfs-provisioner:v{{ .Version }}"
  - "quay.io/ccremer/zfs-provisioner:v{{ .Version }}"

  # For prereleases, updating `latest` and the floating tags of the major version does not make sense.
  # Only the image for the exact version should be pushed.
  - "{{ if not .Prerelease }}docker.io/ccremer/zfs-provisioner:v{{ .Major }}{{ end }}"
  - "{{ if not .Prerelease }}quay.io/ccremer/zfs-provisioner:v{{ .Major }}{{ end }}"

  - "{{ if not .Prerelease }}docker.io/ccremer/zfs-provisioner:latest{{ end }}"
  - "{{ if not .Prerelease }}quay.io/ccremer/zfs-provisioner:latest{{ end }}"

  extra_files:
  - docker/zfs.sh
  - docker/update-permissions.sh
  dockerfile: docker/Dockerfile

release:
  prerelease: auto
  github:
    owner: ccremer
    name: kubernetes-zfs-provisioner
